version: '3'
services:
  zoo1:
    container_name: zoo1
    image: 'docker.io/bitnami/zookeeper:3.9'
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      - ZOO_SERVER_ID=1
      - ZOO_ENABLE_AUTH=yes
      #- ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_MAX_CLIENT_CNXNS=0
      #- ZOO_DATA_LOG_DIR=logs
      - ZOO_SERVERS=server.1=zoo1:2181:2181 #можно добавлять список серверов для кластера
    volumes:
      - "./zoo1-data:/bitnami/zookeeper"
    restart: always

  kafka1:
    container_name: kafka1
    image: docker.io/bitnami/kafka:3.3
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
    volumes:
      - "./kafka1-data:/bitnami/kafka"
    restart: always
    depends_on:
      - zoo1